site_title: 学習指導要領LOD
base_uri: https://w3id.org/jp-textbook/
uri_mappings:
  - regexp: !ruby/regexp /^(A[ABC])(\d{9})(\d{3})$/
    path: '\1/\2/\3'
top_class: https://w3id.org/jp-textbook/CurriculumGuideline
top_additional_property:
  - https://w3id.org/jp-textbook/hasSubjectArea
locale: ja
breadcrumbs:
  - property: https://w3id.org/jp-textbook/subject
  - property: https://w3id.org/jp-textbook/subjectArea
  - property: https://w3id.org/jp-textbook/curriculum
admin_name: 教科書LODプロジェクト
copyright_year: 2017-2022
css_file: style.css
logo: logo.png
additional_link:
  - label: English
    href: https://w3id.org/jp-textbook/en/
