site_title: 学習指導要領LOD
base_uri: https://w3id.org/jp-textbook/
uri_mappings:
  - regexp: !ruby/regexp /^(A[AB])(\d{9})(\d{3})$/
    path: '\1/\2/\3'
locale: ja
breadcrumbs:
  - property: http://schema.org/hasPart
    inverse: true
    label: https://w3id.org/jp-cos/sectionNumber
  - property: https://w3id.org/jp-cos/courseOfStudy
top_class: https://w3id.org/jp-textbook/curriculum/SubjectArea
admin_name: 教科書LOD
copyright_year: 2017-2022
css_file: style.css
logo: logo.png
additional_link:
  - label: English
    href: https://w3id.org/jp-textbook/en/
